import { InvoiceTableProps, TableData } from "@/interface/interfaces";

export const users: TableData[] = [
  {
    _id: crypto.randomUUID(),
    nombre: "Edgardo",
    apellido: "Marcano",
    cedula: "V25317338",
    edad: 22,
    peso: 70,
    fechaRegistro: "20/10/2024",
    ultimoPago: "20/11/2024",
    diasEnMora: "14 días",
    trainer: "Juan Perez",
    ultimaActualizacion: "27/11/2024",
    // acciones: "",
  },
  {
    nombre: "Luis",
    apellido: "Gómez",
    cedula: "V19847291",
    edad: 30,
    peso: 78,
    fechaRegistro: "15/09/2024",
    ultimoPago: "15/10/2024",
    diasEnMora: "30 días",
    trainer: "Carlos Mendoza",
    ultimaActualizacion: "20/11/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Andrea",
    apellido: "Fernández",
    cedula: "V30765412",
    edad: 25,
    peso: 65,
    fechaRegistro: "10/08/2024",
    ultimoPago: "10/09/2024",
    diasEnMora: "40 días",
    trainer: "María López",
    ultimaActualizacion: "18/10/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "José",
    apellido: "Ramírez",
    cedula: "V27983456",
    edad: 28,
    peso: 85,
    fechaRegistro: "05/07/2024",
    ultimoPago: "05/08/2024",
    diasEnMora: "60 días",
    trainer: "Javier Ríos",
    ultimaActualizacion: "12/09/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Sofía",
    apellido: "Martínez",
    cedula: "V25478963",
    edad: 21,
    peso: 60,
    fechaRegistro: "25/06/2024",
    ultimoPago: "25/07/2024",
    diasEnMora: "80 días",
    trainer: "Ana Suárez",
    ultimaActualizacion: "05/09/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Carlos",
    apellido: "Díaz",
    cedula: "V31247895",
    edad: 35,
    peso: 90,
    fechaRegistro: "30/05/2024",
    ultimoPago: "30/06/2024",
    diasEnMora: "100 días",
    trainer: "Fernando Torres",
    ultimaActualizacion: "02/08/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Valeria",
    apellido: "Castillo",
    cedula: "V28974321",
    edad: 27,
    peso: 68,
    fechaRegistro: "12/04/2024",
    ultimoPago: "12/05/2024",
    diasEnMora: "120 días",
    trainer: "Gabriel Ortega",
    ultimaActualizacion: "20/07/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Alejandro",
    apellido: "Morales",
    cedula: "V32147856",
    edad: 23,
    peso: 75,
    fechaRegistro: "08/03/2024",
    ultimoPago: "08/04/2024",
    diasEnMora: "140 días",
    trainer: "Mónica Herrera",
    ultimaActualizacion: "10/06/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Natalia",
    apellido: "Rojas",
    cedula: "V29475631",
    edad: 32,
    peso: 73,
    fechaRegistro: "01/02/2024",
    ultimoPago: "01/03/2024",
    diasEnMora: "160 días",
    trainer: "Ricardo Pérez",
    ultimaActualizacion: "12/05/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
  {
    nombre: "Miguel",
    apellido: "Gutiérrez",
    cedula: "V31647892",
    edad: 26,
    peso: 82,
    fechaRegistro: "20/01/2024",
    ultimoPago: "20/02/2024",
    diasEnMora: "180 días",
    trainer: "Beatriz Sánchez",
    ultimaActualizacion: "02/04/2024",
    _id: crypto.randomUUID(),
    // acciones: "",
  },
];

export const invoices: InvoiceTableProps[] = [
  {
    _id: crypto.randomUUID(),
    mes: "Enero",
    numero: "INV001",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: crypto.randomUUID(),
    mes: "Febrero",
    numero: "INV002",
    tipo: "semanal",
    status: "Mora",
    corte: new Date(),
    // acciones: "",
  },

  {
    _id: crypto.randomUUID(),
    mes: "Marzo",
    numero: "INV003",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: crypto.randomUUID(),
    mes: "Abril",
    numero: "INV004",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: crypto.randomUUID(),
    mes: "Mayo",
    numero: "INV005",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
];
