import { InvoiceTableProps, UserBody } from "@/interface/interfaces";

function convertToDate(dateStr: string): Date {
  const [day, month, year] = dateStr.split("/").map(Number);
  return new Date(year, month - 1, day); // Restamos 1 porque los meses en JS van de 0-11
}

export const users: UserBody[] = [
  {
    _id: 1,
    nombre: "Edgardo",
    apellido: "Marcano",
    cedula: "V25317338",
    edad: 22,
    peso: 70,
    fechaRegistro: convertToDate("20/10/2024"),
    ultimoPago: convertToDate("20/11/2024"),
    diasEnMora: 2,
    trainer: "Juan Perez",
    ultimaActualizacion: convertToDate("27/11/2024"),
    // acciones: "",
  },
  {
    _id: 2,
    nombre: "Luis",
    apellido: "Gómez",
    cedula: "V19847291",
    edad: 30,
    peso: 78,
    fechaRegistro: convertToDate("15/09/2024"),
    ultimoPago: convertToDate("15/10/2024"),
    diasEnMora: 3,
    trainer: "Carlos Mendoza",
    ultimaActualizacion: convertToDate("20/11/2024"),
    // acciones: "",
  },
  {
    _id: 3,
    nombre: "Andrea",
    apellido: "Fernández",
    cedula: "V30765412",
    edad: 25,
    peso: 65,
    fechaRegistro: convertToDate("10/08/2024"),
    ultimoPago: convertToDate("10/09/2024"),
    diasEnMora: 4,
    trainer: "María López",
    ultimaActualizacion: convertToDate("18/10/2024"),
    // acciones: "",
  },
  {
    _id: 4,
    nombre: "José",
    apellido: "Ramírez",
    cedula: "V27983456",
    edad: 28,
    peso: 85,
    fechaRegistro: convertToDate("05/07/2024"),
    ultimoPago: convertToDate("05/08/2024"),
    diasEnMora: 6,
    trainer: "Javier Ríos",
    ultimaActualizacion: convertToDate("12/09/2024"),
    // acciones: "",
  },
  {
    _id: 5,
    nombre: "Sofía",
    apellido: "Martínez",
    cedula: "V25478963",
    edad: 21,
    peso: 60,
    fechaRegistro: convertToDate("25/06/2024"),
    ultimoPago: convertToDate("25/07/2024"),
    diasEnMora: 8,
    trainer: "Ana Suárez",
    ultimaActualizacion: convertToDate("05/09/2024"),
    // acciones: "",
  },
  {
    _id: 6,
    nombre: "Carlos",
    apellido: "Díaz",
    cedula: "V31247895",
    edad: 35,
    peso: 90,
    fechaRegistro: convertToDate("30/05/2024"),
    ultimoPago: convertToDate("30/06/2024"),
    diasEnMora: 10,
    trainer: "Fernando Torres",
    ultimaActualizacion: convertToDate("02/08/2024"),
    // acciones: "",
  },
  {
    _id: 7,
    nombre: "Valeria",
    apellido: "Castillo",
    cedula: "V28974321",
    edad: 27,
    peso: 68,
    fechaRegistro: convertToDate("12/04/2024"),
    ultimoPago: convertToDate("12/05/2024"),
    diasEnMora: 12,
    trainer: "Gabriel Ortega",
    ultimaActualizacion: convertToDate("20/07/2024"),
    // acciones: "",
  },
  {
    _id: 8,
    nombre: "Alejandro",
    apellido: "Morales",
    cedula: "V32147856",
    edad: 23,
    peso: 75,
    fechaRegistro: convertToDate("08/03/2024"),
    ultimoPago: convertToDate("08/04/2024"),
    diasEnMora: 14,
    trainer: "Mónica Herrera",
    ultimaActualizacion: convertToDate("10/06/2024"),
    // acciones: "",
  },
  {
    _id: 9,
    nombre: "Natalia",
    apellido: "Rojas",
    cedula: "V29475631",
    edad: 32,
    peso: 73,
    fechaRegistro: convertToDate("01/02/2024"),
    ultimoPago: convertToDate("01/03/2024"),
    diasEnMora: 16,
    trainer: "Ricardo Pérez",
    ultimaActualizacion: convertToDate("12/05/2024"),
    // acciones: "",
  },
  {
    _id: 10,
    nombre: "Miguel",
    apellido: "Gutiérrez",
    cedula: "V31647892",
    edad: 26,
    peso: 82,
    fechaRegistro: convertToDate("20/01/2024"),
    ultimoPago: convertToDate("20/02/2024"),
    diasEnMora: 18,
    trainer: "Beatriz Sánchez",
    ultimaActualizacion: convertToDate("02/04/2024"),
    // acciones: "",
  },
];

export const invoices: InvoiceTableProps[] = [
  {
    _id: 1,
    mes: "Enero",
    numero: "INV001",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: 2,
    mes: "Febrero",
    numero: "INV002",
    tipo: "semanal",
    status: "Mora",
    corte: new Date(),
    // acciones: "",
  },

  {
    _id: 3,
    mes: "Marzo",
    numero: "INV003",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: 4,
    mes: "Abril",
    numero: "INV004",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
  {
    _id: 5,
    mes: "Mayo",
    numero: "INV005",
    tipo: "semanal",
    status: "Pago",
    corte: new Date(),
    // acciones: "",
  },
];
